"""
Profile 3 constants — 120 kg / 190 cm.
Exercises: bss (3 days/wk) + pull_up (4 days/wk).
pull_up uses BAR_ONLY only — absolute novice, no assisting equipment.

Section A: hand-authored.
Section B: GENERATED — run regenerate.py to fill in.
"""

# ===========================================================================
# Section A: hand-authored
# ===========================================================================

P3_HEIGHT_CM = 190
P3_BODYWEIGHT_KG = 120.0

P3_BSS_DAYS = 3
P3_PULL_UP_DAYS = 4

P3_BSS_TARGET_REPS = 1
P3_BSS_TARGET_WEIGHT_KG = 150.0

P3_PULL_UP_TARGET_REPS = 20
P3_PULL_UP_TARGET_WEIGHT_KG = 15.0

P3_BSS_AVAILABLE_ITEMS = ["DUMBBELLS"]
P3_BSS_WEIGHTS_KG = list(range(2, 38, 2))  # 2 → 36 step 2

P3_PULL_UP_AVAILABLE_ITEMS = ["BAR_ONLY"]  # no bands, no belt — tests absolute novice path

# --- Layer 3 ---
P3_BSS_IMPROVED_TEST = {
    "date": "2026-01-11",
    "session_type": "TEST",
    "bodyweight_kg": 120.0,
    "sets": [{"reps": 6, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": None}],
    "grip": "standard",
}

P3_PULL_UP_IMPROVED_TEST = {
    "date": "2026-01-11",
    "session_type": "TEST",
    "bodyweight_kg": 120.0,
    "sets": [{"reps": 8, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": None}],
    "grip": "pronated",
}

# --- Layer 4 ---
P3_BSS_OVERPERFORMANCE = {
    "date": "2026-01-13",
    "session_type": "S",
    "bodyweight_kg": 120.0,
    "sets": [
        {"reps": 7, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
        {"reps": 7, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
        {"reps": 6, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
        {"reps": 6, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
    ],
    "grip": "standard",
}

P3_PULL_UP_OVERPERFORMANCE = {
    "date": "2026-01-13",
    "session_type": "S",
    "bodyweight_kg": 120.0,
    "sets": [
        {"reps": 6, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 4, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
    ],
    "grip": "pronated",
}

# ===========================================================================
# Section B: GENERATED
# ===========================================================================

P3_BSS_STATUS = {'training_max': 2,
 'latest_test_max': 3,
 'trend_slope_per_week': 0.0,
 'is_plateau': False,
 'deload_recommended': True,
 'readiness_z_score': 2.1998,
 'fitness': 216.8666,
 'fatigue': 142.4388}
P3_PULL_UP_STATUS = {'training_max': 4,
 'latest_test_max': 5,
 'trend_slope_per_week': 0.0,
 'is_plateau': False,
 'deload_recommended': True,
 'readiness_z_score': 1.914,
 'fitness': 74.8788,
 'fatigue': 60.6114}

P3_BSS_FUTURE_SESSIONS = [{'date': '2026-01-13',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 72.0, 'rest_s': 240}]},
 {'date': '2026-01-15',
  'type': 'E',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]},
 {'date': '2026-01-17',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195}]},
 {'date': '2026-01-20',
  'type': 'H',
  'prescribed_sets': [{'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120}]},
 {'date': '2026-01-22',
  'type': 'E',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]},
 {'date': '2026-01-24',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195}]},
 {'date': '2026-01-27',
  'type': 'H',
  'prescribed_sets': [{'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120}]},
 {'date': '2026-01-29',
  'type': 'E',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]},
 {'date': '2026-01-31',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195}]},
 {'date': '2026-02-03',
  'type': 'H',
  'prescribed_sets': [{'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                      {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120}]},
 {'date': '2026-02-05',
  'type': 'E',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]},
 {'date': '2026-02-07',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                      {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195}]}]
P3_PULL_UP_FUTURE_SESSIONS = [{'date': '2026-01-13',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-01-15',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
 {'date': '2026-01-16',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-01-18',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
 {'date': '2026-01-20',
  'type': 'T',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90}]},
 {'date': '2026-01-21',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
 {'date': '2026-01-23',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-01-25',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
 {'date': '2026-01-27',
  'type': 'T',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90}]},
 {'date': '2026-01-28',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
 {'date': '2026-01-30',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-02-01',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
 {'date': '2026-02-03',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-02-05',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
 {'date': '2026-02-06',
  'type': 'S',
  'prescribed_sets': [{'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-02-08',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]}]

P3_BSS_DONE_METRICS = [{'volume_session': 495.6, 'avg_volume_set': 495.6, 'estimated_1rm': 176.01},
 {'volume_session': 5286.4, 'avg_volume_set': 1321.6, 'estimated_1rm': 207.02},
 {'volume_session': 2643.2, 'avg_volume_set': 660.8, 'estimated_1rm': 181.27},
 {'volume_session': 5286.4, 'avg_volume_set': 1321.6, 'estimated_1rm': 207.02},
 {'volume_session': 3304.0, 'avg_volume_set': 660.8, 'estimated_1rm': 181.27},
 {'volume_session': 7449.6, 'avg_volume_set': 1862.4, 'estimated_1rm': 208.13},
 {'volume_session': 5286.4, 'avg_volume_set': 1321.6, 'estimated_1rm': 207.02},
 {'volume_session': 3304.0, 'avg_volume_set': 660.8, 'estimated_1rm': 181.27},
 {'volume_session': 5286.4, 'avg_volume_set': 1321.6, 'estimated_1rm': 207.02},
 {'volume_session': 3304.0, 'avg_volume_set': 660.8, 'estimated_1rm': 181.27}]
P3_PULL_UP_DONE_METRICS = [{'volume_session': 600.0, 'avg_volume_set': 600.0, 'estimated_1rm': 135.73},
 {'volume_session': 1920.0, 'avg_volume_set': 480.0, 'estimated_1rm': 131.67},
 {'volume_session': 1800.0, 'avg_volume_set': 360.0, 'estimated_1rm': 127.85},
 {'volume_session': 2880.0, 'avg_volume_set': 480.0, 'estimated_1rm': 131.67},
 {'volume_session': 1920.0, 'avg_volume_set': 480.0, 'estimated_1rm': 131.67},
 {'volume_session': 1800.0, 'avg_volume_set': 360.0, 'estimated_1rm': 127.85},
 {'volume_session': 2880.0, 'avg_volume_set': 480.0, 'estimated_1rm': 131.67},
 {'volume_session': 2400.0, 'avg_volume_set': 600.0, 'estimated_1rm': 135.73},
 {'volume_session': 1800.0, 'avg_volume_set': 360.0, 'estimated_1rm': 127.85},
 {'volume_session': 2400.0, 'avg_volume_set': 600.0, 'estimated_1rm': 135.73}]

P3_BSS_AFTER_IMPROVED_TEST = {'status': {'training_max': 5,
            'latest_test_max': 6,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': True,
            'readiness_z_score': 0.849,
            'fitness': 54.4133,
            'fatigue': 18.7309},
 'future_sessions': [{'date': '2026-01-13',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 8, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 8, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 8, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 8, 'weight_kg': 72.0, 'rest_s': 120}]},
                     {'date': '2026-01-15',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75},
                                          {'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]},
                     {'date': '2026-01-17',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 4, 'weight_kg': 72.0, 'rest_s': 195},
                                          {'reps': 4, 'weight_kg': 72.0, 'rest_s': 195},
                                          {'reps': 4, 'weight_kg': 72.0, 'rest_s': 195}]},
                     {'date': '2026-01-20',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 8, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 8, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 8, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 8, 'weight_kg': 72.0, 'rest_s': 120}]}]}
P3_PULL_UP_AFTER_IMPROVED_TEST = {'status': {'training_max': 7,
            'latest_test_max': 8,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': True,
            'readiness_z_score': 0.8694,
            'fitness': 18.3555,
            'fatigue': 11.6013},
 'future_sessions': [{'date': '2026-01-13',
                      'type': 'T',
                      'prescribed_sets': [{'reps': 2, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 90}]},
                     {'date': '2026-01-14',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
                     {'date': '2026-01-16',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240}]},
                     {'date': '2026-01-18',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150}]}]}

P3_BSS_AFTER_OVERPERFORMANCE = {'status': {'training_max': 2,
            'latest_test_max': 3,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': False,
            'readiness_z_score': 0.1066,
            'fitness': 75.1258,
            'fatigue': 64.3432},
 'future_sessions': [{'date': '2026-01-15',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]},
                     {'date': '2026-01-17',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                                          {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195},
                                          {'reps': 5, 'weight_kg': 72.0, 'rest_s': 195}]},
                     {'date': '2026-01-20',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120},
                                          {'reps': 9, 'weight_kg': 72.0, 'rest_s': 120}]},
                     {'date': '2026-01-22',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 10, 'weight_kg': 72.0, 'rest_s': 75}]}]}
P3_PULL_UP_AFTER_OVERPERFORMANCE = {'status': {'training_max': 4,
            'latest_test_max': 5,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': False,
            'readiness_z_score': -0.2064,
            'fitness': 26.3466,
            'fatigue': 28.751},
 'future_sessions': [{'date': '2026-01-15',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
                     {'date': '2026-01-16',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 5, 'weight_kg': 0.0, 'rest_s': 240}]},
                     {'date': '2026-01-18',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
                     {'date': '2026-01-20',
                      'type': 'T',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 90}]}]}
