"""
Profile 2 constants — 80 kg / 180 cm.
Exercises: pull_up (4 days/wk) + dip (4 days/wk).

Section A: hand-authored.
Section B: GENERATED — run regenerate.py to fill in.
"""

# ===========================================================================
# Section A: hand-authored
# ===========================================================================

P2_HEIGHT_CM = 180
P2_BODYWEIGHT_KG = 80.0

P2_PULL_UP_DAYS = 4
P2_DIP_DAYS = 4

P2_PULL_UP_TARGET_REPS = 30
P2_PULL_UP_TARGET_WEIGHT_KG = 0.0

P2_DIP_TARGET_REPS = 12
P2_DIP_TARGET_WEIGHT_KG = 50.0

P2_PULL_UP_AVAILABLE_ITEMS = ["WEIGHT_BELT", "BAR_ONLY"]
P2_DIP_AVAILABLE_ITEMS = ["WEIGHT_BELT", "PARALLEL_BARS"]

# --- Layer 3 ---
P2_PULL_UP_IMPROVED_TEST = {
    "date": "2026-01-11",
    "session_type": "TEST",
    "bodyweight_kg": 80.0,
    "sets": [{"reps": 18, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": None}],
    "grip": "pronated",
}

P2_DIP_IMPROVED_TEST = {
    "date": "2026-01-11",
    "session_type": "TEST",
    "bodyweight_kg": 80.0,
    "sets": [{"reps": 11, "rest_seconds": 180, "added_weight_kg": 10.0, "rir_reported": None}],
    "grip": "standard",
}

# --- Layer 4 ---
P2_PULL_UP_OVERPERFORMANCE = {
    "date": "2026-01-13",
    "session_type": "S",
    "bodyweight_kg": 80.0,
    "sets": [
        {"reps": 18, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 17, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 16, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 15, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
        {"reps": 14, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
    ],
    "grip": "pronated",
}

P2_DIP_OVERPERFORMANCE = {
    "date": "2026-01-13",
    "session_type": "S",
    "bodyweight_kg": 80.0,
    "sets": [
        {"reps": 10, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
        {"reps": 9,  "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
        {"reps": 9,  "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
        {"reps": 8,  "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
    ],
    "grip": "standard",
}

# --- Layer 5: 15-week dip simulation (fresh profile dir, P2 spec) ---
# Phase 1 (1-7): normal load, rir=2.  Phase 2 (8-14): dense+rir=0.  Phase 3 (15-20): deload+new best.
P2_DIP_15W_SESSIONS = [
    # ---- Phase 1 ----
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 180, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-06", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-10", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-15", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-20", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-24", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-27", "session_type": "TEST", "bodyweight_kg": 80.0,
     "sets": [{"reps": 9, "rest_seconds": 180, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    # ---- Phase 2 (sessions 8-14): overtraining ----
    {"date": "2025-11-03", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 7, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 7, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    {"date": "2025-11-05", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 5, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    {"date": "2025-11-07", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 7, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 7, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 6, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 6, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 6, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    {"date": "2025-11-10", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 10, "rest_seconds": 45, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 9,  "rest_seconds": 45, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 9,  "rest_seconds": 45, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 8,  "rest_seconds": 45, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 8,  "rest_seconds": 45, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 7,  "rest_seconds": 45, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    {"date": "2025-11-12", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    {"date": "2025-11-14", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 7, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 6, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 6, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 5, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0},
              {"reps": 5, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    {"date": "2025-11-17", "session_type": "TEST", "bodyweight_kg": 80.0,
     "sets": [{"reps": 9, "rest_seconds": 180, "added_weight_kg": 10.0, "rir_reported": 0}],
     "grip": "standard"},
    # ---- Phase 3: deload + recovery (sessions 15-20) ----
    {"date": "2025-11-24", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 8, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 8, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 3}],
     "grip": "standard"},
    {"date": "2025-12-01", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 8, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 8, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 3}],
     "grip": "standard"},
    {"date": "2025-12-08", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 180, "added_weight_kg": 5.0, "rir_reported": 3},
              {"reps": 8, "rest_seconds": 180, "added_weight_kg": 5.0, "rir_reported": 3},
              {"reps": 8, "rest_seconds": 180, "added_weight_kg": 5.0, "rir_reported": 3}],
     "grip": "standard"},
    {"date": "2025-12-15", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-12-22", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2026-01-05", "session_type": "TEST", "bodyweight_kg": 80.0,
     "sets": [{"reps": 11, "rest_seconds": 180, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
]

P2_DIP_15W_CHECKPOINT_IDX = [7, 14, 20]

# ===========================================================================
# Section B: GENERATED
# ===========================================================================

P2_PULL_UP_STATUS = {'training_max': 13,
 'latest_test_max': 15,
 'trend_slope_per_week': 0.0,
 'is_plateau': False,
 'deload_recommended': True,
 'readiness_z_score': 1.4373,
 'fitness': 177.3548,
 'fatigue': 154.8625}
P2_DIP_STATUS = {'training_max': 7,
 'latest_test_max': 8,
 'trend_slope_per_week': 0.0,
 'is_plateau': False,
 'deload_recommended': True,
 'readiness_z_score': 1.5213,
 'fitness': 152.5648,
 'fatigue': 131.879}

P2_PULL_UP_FUTURE_SESSIONS = [{'date': '2026-01-13',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 14, 'weight_kg': 20.0, 'rest_s': 240}]},
 {'date': '2026-01-15',
  'type': 'E',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60}]},
 {'date': '2026-01-16',
  'type': 'S',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 12.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 12.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 12.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 12.5, 'rest_s': 240}]},
 {'date': '2026-01-18',
  'type': 'H',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150}]},
 {'date': '2026-01-20',
  'type': 'T',
  'prescribed_sets': [{'reps': 4, 'weight_kg': 10.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 10.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 10.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 10.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 10.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 10.0, 'rest_s': 75}]},
 {'date': '2026-01-21',
  'type': 'E',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60}]},
 {'date': '2026-01-23',
  'type': 'S',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 12.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 12.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 12.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 12.5, 'rest_s': 240}]},
 {'date': '2026-01-25',
  'type': 'H',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 5.5, 'rest_s': 150}]},
 {'date': '2026-01-27',
  'type': 'T',
  'prescribed_sets': [{'reps': 4, 'weight_kg': 11.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 11.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 11.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 11.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 11.0, 'rest_s': 75},
                      {'reps': 4, 'weight_kg': 11.0, 'rest_s': 75}]},
 {'date': '2026-01-28',
  'type': 'E',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60}]},
 {'date': '2026-01-30',
  'type': 'S',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 13.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 13.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 13.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 13.5, 'rest_s': 240}]},
 {'date': '2026-02-01',
  'type': 'H',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150}]},
 {'date': '2026-02-03',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 15, 'weight_kg': 20.0, 'rest_s': 240}]},
 {'date': '2026-02-05',
  'type': 'E',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 5, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 60}]},
 {'date': '2026-02-06',
  'type': 'S',
  'prescribed_sets': [{'reps': 6, 'weight_kg': 13.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 13.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 13.5, 'rest_s': 240},
                      {'reps': 6, 'weight_kg': 13.5, 'rest_s': 240}]},
 {'date': '2026-02-08',
  'type': 'H',
  'prescribed_sets': [{'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150},
                      {'reps': 10, 'weight_kg': 6.5, 'rest_s': 150}]}]
P2_DIP_FUTURE_SESSIONS = [{'date': '2026-01-13',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 8, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-01-15',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67}]},
 {'date': '2026-01-16',
  'type': 'S',
  'prescribed_sets': [{'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-01-18',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
 {'date': '2026-01-20',
  'type': 'T',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
 {'date': '2026-01-21',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67}]},
 {'date': '2026-01-23',
  'type': 'S',
  'prescribed_sets': [{'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-01-25',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
 {'date': '2026-01-27',
  'type': 'T',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]},
 {'date': '2026-01-28',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67}]},
 {'date': '2026-01-30',
  'type': 'S',
  'prescribed_sets': [{'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-02-01',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
 {'date': '2026-02-03',
  'type': 'TEST',
  'prescribed_sets': [{'reps': 9, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-02-05',
  'type': 'E',
  'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                      {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67}]},
 {'date': '2026-02-06',
  'type': 'S',
  'prescribed_sets': [{'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                      {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240}]},
 {'date': '2026-02-08',
  'type': 'H',
  'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                      {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]}]

P2_PULL_UP_DONE_METRICS = [{'volume_session': 1200.0, 'avg_volume_set': 1200.0, 'estimated_1rm': 112.44},
 {'volume_session': 2000.0, 'avg_volume_set': 400.0, 'estimated_1rm': 90.49},
 {'volume_session': 4000.0, 'avg_volume_set': 800.0, 'estimated_1rm': 106.87},
 {'volume_session': 5120.0, 'avg_volume_set': 640.0, 'estimated_1rm': 100.25},
 {'volume_session': 2000.0, 'avg_volume_set': 400.0, 'estimated_1rm': 90.49},
 {'volume_session': 4000.0, 'avg_volume_set': 800.0, 'estimated_1rm': 106.87},
 {'volume_session': 5120.0, 'avg_volume_set': 640.0, 'estimated_1rm': 100.25},
 {'volume_session': 1440.0, 'avg_volume_set': 240.0, 'estimated_1rm': 85.23},
 {'volume_session': 2000.0, 'avg_volume_set': 400.0, 'estimated_1rm': 90.49},
 {'volume_session': 4000.0, 'avg_volume_set': 800.0, 'estimated_1rm': 106.87}]
P2_DIP_DONE_METRICS = [{'volume_session': 668.8, 'avg_volume_set': 668.8, 'estimated_1rm': 104.76},
 {'volume_session': 1672.0, 'avg_volume_set': 418.0, 'estimated_1rm': 94.56},
 {'volume_session': 2675.2, 'avg_volume_set': 668.8, 'estimated_1rm': 104.76},
 {'volume_session': 4180.0, 'avg_volume_set': 836.0, 'estimated_1rm': 111.68},
 {'volume_session': 1672.0, 'avg_volume_set': 418.0, 'estimated_1rm': 94.56},
 {'volume_session': 2675.2, 'avg_volume_set': 668.8, 'estimated_1rm': 104.76},
 {'volume_session': 4180.0, 'avg_volume_set': 836.0, 'estimated_1rm': 111.68},
 {'volume_session': 1254.0, 'avg_volume_set': 250.8, 'estimated_1rm': 89.07},
 {'volume_session': 1672.0, 'avg_volume_set': 418.0, 'estimated_1rm': 94.56},
 {'volume_session': 2675.2, 'avg_volume_set': 668.8, 'estimated_1rm': 104.76}]

P2_PULL_UP_AFTER_IMPROVED_TEST = {'status': {'training_max': 16,
            'latest_test_max': 18,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': True,
            'readiness_z_score': 0.8838,
            'fitness': 38.8295,
            'fatigue': 26.1015},
 'future_sessions': [{'date': '2026-01-13',
                      'type': 'T',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 16.0, 'rest_s': 75}]},
                     {'date': '2026-01-14',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 7, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 6, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 5, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 4, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60}]},
                     {'date': '2026-01-16',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 5, 'weight_kg': 18.5, 'rest_s': 240},
                                          {'reps': 5, 'weight_kg': 18.5, 'rest_s': 240},
                                          {'reps': 5, 'weight_kg': 18.5, 'rest_s': 240},
                                          {'reps': 5, 'weight_kg': 18.5, 'rest_s': 240}]},
                     {'date': '2026-01-18',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150}]}]}
P2_DIP_AFTER_IMPROVED_TEST = {'status': {'training_max': 9,
            'latest_test_max': 11,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': True,
            'readiness_z_score': 0.9742,
            'fitness': 31.6923,
            'fatigue': 19.0335},
 'future_sessions': [{'date': '2026-01-13',
                      'type': 'T',
                      'prescribed_sets': [{'reps': 2, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 2, 'weight_kg': 0.0, 'rest_s': 75}]},
                     {'date': '2026-01-14',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67}]},
                     {'date': '2026-01-16',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 240}]},
                     {'date': '2026-01-18',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 6, 'weight_kg': 0.0, 'rest_s': 150}]}]}

P2_PULL_UP_AFTER_OVERPERFORMANCE = {'status': {'training_max': 13,
            'latest_test_max': 15,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': False,
            'readiness_z_score': -0.6167,
            'fitness': 70.5807,
            'fatigue': 92.0011},
 'future_sessions': [{'date': '2026-01-15',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 6, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 5, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 4, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60},
                                          {'reps': 3, 'weight_kg': 2.5, 'rest_s': 60}]},
                     {'date': '2026-01-16',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 6, 'weight_kg': 18.5, 'rest_s': 240},
                                          {'reps': 6, 'weight_kg': 18.5, 'rest_s': 240},
                                          {'reps': 6, 'weight_kg': 18.5, 'rest_s': 240},
                                          {'reps': 6, 'weight_kg': 18.5, 'rest_s': 240}]},
                     {'date': '2026-01-18',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150},
                                          {'reps': 10, 'weight_kg': 11.0, 'rest_s': 150}]},
                     {'date': '2026-01-20',
                      'type': 'T',
                      'prescribed_sets': [{'reps': 4, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 4, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 4, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 4, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 4, 'weight_kg': 16.0, 'rest_s': 75},
                                          {'reps': 4, 'weight_kg': 16.0, 'rest_s': 75}]}]}
P2_DIP_AFTER_OVERPERFORMANCE = {'status': {'training_max': 7,
            'latest_test_max': 8,
            'trend_slope_per_week': 0.0,
            'is_plateau': False,
            'deload_recommended': False,
            'readiness_z_score': 0.1769,
            'fitness': 45.845,
            'fatigue': 49.4012},
 'future_sessions': [{'date': '2026-01-15',
                      'type': 'E',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 67}]},
                     {'date': '2026-01-16',
                      'type': 'S',
                      'prescribed_sets': [{'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240},
                                          {'reps': 4, 'weight_kg': 0.0, 'rest_s': 240}]},
                     {'date': '2026-01-18',
                      'type': 'H',
                      'prescribed_sets': [{'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150},
                                          {'reps': 7, 'weight_kg': 0.0, 'rest_s': 150}]},
                     {'date': '2026-01-20',
                      'type': 'T',
                      'prescribed_sets': [{'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75},
                                          {'reps': 3, 'weight_kg': 0.0, 'rest_s': 75}]}]}

P2_DIP_15W_CHECKPOINTS = {7: {'is_plateau': False,
     'deload_recommended': True,
     'readiness_z_score': 2.0547,
     'readiness_z_score_min': 1.5547,
     'readiness_z_score_max': 2.5547},
 14: {'is_plateau': False,
      'deload_recommended': True,
      'readiness_z_score': 2.7319,
      'readiness_z_score_min': 2.1855,
      'readiness_z_score_max': 3.2783},
 20: {'is_plateau': False,
      'deload_recommended': True,
      'readiness_z_score': 0.8495,
      'readiness_z_score_min': 0.3495,
      'readiness_z_score_max': 1.3495}}
