"""
Deterministic session histories for all 3 profiles.
Each list is logged once (session-scoped fixture) and remains in the profile for all tests.

Dates: all before 2026-01-12 (frozen today).
Plan start is set to 2026-01-13 per exercise after history is logged.
"""

# ---------------------------------------------------------------------------
# Profile 1 — 50 kg / 160 cm
# ---------------------------------------------------------------------------

# dip: 1 day/wk → ~7 days apart; 10 sessions from 2025-10-01
P1_DIP_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 50.0,
     "sets": [{"reps": 3, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": None}],
     "grip": "standard"},
    {"date": "2025-10-08", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-15", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-22", "session_type": "E", "bodyweight_kg": 50.0,
     "sets": [{"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-29", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 2, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 2, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 2, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-05", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-12", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-19", "session_type": "E", "bodyweight_kg": 50.0,
     "sets": [{"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-26", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 2, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 2, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 2, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-12-03", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "standard"},
]

# incline_db_press: 2 days/wk → ~3-4 days apart; 10 sessions from 2025-10-01
# Available weights: 1.0, 2.5, 4.0, 5.5, 7.0, 8.5, 10.0 …
P1_INCLINE_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 50.0,
     "sets": [{"reps": 8, "rest_seconds": 180, "added_weight_kg": 4.0, "rir_reported": None}],
     "grip": "standard"},
    {"date": "2025-10-05", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 4.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-09", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-13", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 5.5, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-17", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 5.5, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-21", "session_type": "E", "bodyweight_kg": 50.0,
     "sets": [{"reps": 12, "rest_seconds": 60, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 60, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 60, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 60, "added_weight_kg": 4.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 60, "added_weight_kg": 4.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-25", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 210, "added_weight_kg": 7.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 7.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 7.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 7.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-29", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 7.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 7.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 7.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 7.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-02", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 210, "added_weight_kg": 8.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 8.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 8.5, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 210, "added_weight_kg": 8.5, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-06", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 8.5, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 8.5, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 8.5, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 8.5, "rir_reported": 2}],
     "grip": "standard"},
]

# bss: 3 days/wk → ~2-3 days apart; 10 sessions from 2025-10-01
# Available weights: 2, 4, 6, … 36 (step 2)
P1_BSS_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 180, "added_weight_kg": 12.0, "rir_reported": None}],
     "grip": "standard"},
    {"date": "2025-10-04", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 10, "rest_seconds": 90, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 12.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-07", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 180, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 12.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-10", "session_type": "E", "bodyweight_kg": 50.0,
     "sets": [{"reps": 15, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 15, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 15, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 15, "rest_seconds": 60, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-13", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 10, "rest_seconds": 90, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 12.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-16", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-19", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 10, "rest_seconds": 90, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 14.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-22", "session_type": "E", "bodyweight_kg": 50.0,
     "sets": [{"reps": 15, "rest_seconds": 60, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 15, "rest_seconds": 60, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 15, "rest_seconds": 60, "added_weight_kg": 12.0, "rir_reported": 2},
              {"reps": 15, "rest_seconds": 60, "added_weight_kg": 12.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-25", "session_type": "S", "bodyweight_kg": 50.0,
     "sets": [{"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 180, "added_weight_kg": 14.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-28", "session_type": "H", "bodyweight_kg": 50.0,
     "sets": [{"reps": 10, "rest_seconds": 90, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 14.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 14.0, "rir_reported": 2}],
     "grip": "standard"},
]

# ---------------------------------------------------------------------------
# Profile 2 — 80 kg / 180 cm
# ---------------------------------------------------------------------------

# pull_up: 4 days/wk → every ~2 days; 10 sessions from 2025-10-01
P2_PULL_UP_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 80.0,
     "sets": [{"reps": 15, "rest_seconds": 180, "added_weight_kg": 0.0, "rir_reported": None}],
     "grip": "pronated"},
    {"date": "2025-10-03", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
    {"date": "2025-10-06", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "neutral"},
    {"date": "2025-10-08", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "supinated"},
    {"date": "2025-10-10", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
    {"date": "2025-10-13", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "neutral"},
    {"date": "2025-10-15", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 60, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "supinated"},
    {"date": "2025-10-17", "session_type": "T", "bodyweight_kg": 80.0,
     "sets": [{"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 3}],
     "grip": "pronated"},
    {"date": "2025-10-20", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
    {"date": "2025-10-22", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "neutral"},
]

# dip: 4 days/wk → every ~2 days; 10 sessions from 2025-10-01
P2_DIP_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 180, "added_weight_kg": 10.0, "rir_reported": None}],
     "grip": "standard"},
    {"date": "2025-10-03", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-06", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-08", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-10", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-13", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-15", "session_type": "E", "bodyweight_kg": 80.0,
     "sets": [{"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 10, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-17", "session_type": "T", "bodyweight_kg": 80.0,
     "sets": [{"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 3},
              {"reps": 3, "rest_seconds": 90, "added_weight_kg": 10.0, "rir_reported": 3}],
     "grip": "standard"},
    {"date": "2025-10-20", "session_type": "S", "bodyweight_kg": 80.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 240, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-22", "session_type": "H", "bodyweight_kg": 80.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 10.0, "rir_reported": 2}],
     "grip": "standard"},
]

# ---------------------------------------------------------------------------
# Profile 3 — 120 kg / 190 cm
# ---------------------------------------------------------------------------

# bss: 3 days/wk → ~3-4 days apart; 10 sessions from 2025-10-01
P3_BSS_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 120.0,
     "sets": [{"reps": 3, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": None}],
     "grip": "standard"},
    {"date": "2025-10-05", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-09", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-13", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-17", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-21", "session_type": "E", "bodyweight_kg": 120.0,
     "sets": [{"reps": 12, "rest_seconds": 90, "added_weight_kg": 70.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 90, "added_weight_kg": 70.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 90, "added_weight_kg": 70.0, "rir_reported": 2},
              {"reps": 12, "rest_seconds": 90, "added_weight_kg": 70.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-25", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-10-29", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-02", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 8, "rest_seconds": 150, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
    {"date": "2025-11-06", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 240, "added_weight_kg": 80.0, "rir_reported": 2}],
     "grip": "standard"},
]

# pull_up: 4 days/wk → every ~2 days; 10 sessions from 2025-10-01
# 120 kg bodyweight, BAR_ONLY, absolute novice (starts ~5 reps)
P3_PULL_UP_HISTORY = [
    {"date": "2025-10-01", "session_type": "TEST", "bodyweight_kg": 120.0,
     "sets": [{"reps": 5, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": None}],
     "grip": "pronated"},
    {"date": "2025-10-04", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
    {"date": "2025-10-07", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "neutral"},
    {"date": "2025-10-10", "session_type": "E", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "supinated"},
    {"date": "2025-10-13", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
    {"date": "2025-10-16", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "neutral"},
    {"date": "2025-10-19", "session_type": "E", "bodyweight_kg": 120.0,
     "sets": [{"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 4, "rest_seconds": 90, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "supinated"},
    {"date": "2025-10-22", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
    {"date": "2025-10-25", "session_type": "S", "bodyweight_kg": 120.0,
     "sets": [{"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 3, "rest_seconds": 240, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "neutral"},
    {"date": "2025-10-28", "session_type": "H", "bodyweight_kg": 120.0,
     "sets": [{"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2},
              {"reps": 5, "rest_seconds": 150, "added_weight_kg": 0.0, "rir_reported": 2}],
     "grip": "pronated"},
]
